# Generated by Django 2.2 on 2020-06-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaVentas', '0002_detalle_producto_proveedor_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(),
        ),
    ]
